# Generated by Django 3.0.8 on 2020-08-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200802_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(to='api.Planet'),
        ),
    ]
