# Generated by Django 3.0.8 on 2020-08-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200802_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='opening_crawl',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
