# Generated by Django 3.0.8 on 2020-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200802_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='mass',
            field=models.IntegerField(null=True),
        ),
    ]
